### ISSUE TITLE
split the CI to release driven workflows

### ISSUE THREAD

**Issue by FoSix** [PaloAltoNetworks/pan-os-upgrade-assurance#91]
## problem

Currently the release workflow works in a chain, meaning that all jobs depend on each other, even though not all of them do. It's related to how you pass outputs between jobs (you need to add `needs` which immediately chains jobs).

The problem pops up when one of the chained jobs fails. It causes the other, related/chained jobs to fail as well. For example, a push to GHCR fails, causing the documentation update to fail.

## solution

Split the release to several workflows. The release itself should only do a github release. The other workflows, like publish to PyPI, publish to GHCR and documentation PR to pan.dev should be separate, independent workflows, triggered by a push to a `v***` like tag. This way if any of them should fail, it would not affect the other ones. Re-running or fixing the failed workflows should also be simpler, as it would not require a release to be triggered.

## TODO

three workflows to develop:

- [x] #94
- [x] #95
- [x] #96

**Comment by FoSix** [comment]
three releases to develop:

- [ ] docker image publish
- [ ] PyPI package publish
- [ ] create pan.dev PR
